# Generated by Django 3.0.3 on 2020-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='abordagem',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='conta_banco',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='horario_trabalho',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='quantidade_atend',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
