# Generated by Django 3.1.7 on 2021-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='criado_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
