# Generated by Django 3.0.3 on 2020-09-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='sus',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
