# Generated by Django 3.1.7 on 2021-04-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210417_1508'),
        ('core', '0002_auto_20200927_2221'),
    ]

    operations = [
    ]
