# Generated by Django 3.1.7 on 2021-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20210417_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='tratamento',
            field=models.BooleanField(blank=True, default=1, verbose_name='Tratamento Concluido'),
            preserve_default=False,
        ),
    ]
