# Generated by Django 3.1.7 on 2021-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listaespera_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='tratamento',
            field=models.CharField(blank=True, choices=[('IN', 'Iniciado'), ('CO', 'Concluido'), ('RE', 'RECUSA LIGAÇÃO')], max_length=2, verbose_name='tratamento'),
        ),
    ]
