# Generated by Django 3.1.7 on 2021-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210418_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaespera',
            name='tratamento',
        ),
        migrations.AddField(
            model_name='listaespera',
            name='urgente',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Urgente'),
        ),
    ]
