# Generated by Django 3.1.7 on 2021-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210418_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='urgente',
            field=models.CharField(blank=True, choices=[('U', 'Urgente'), ('R', 'Rotina')], max_length=1, verbose_name='Urgente'),
        ),
    ]
