# Generated by Django 3.1.7 on 2021-04-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20210418_0038'),
        ('controle_usuarios', '0002_auto_20200930_2008'),
        ('core', '0007_auto_20210418_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='sus',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='telefone_fixo',
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='nome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.RemoveField(
            model_name='listaespera',
            name='profissional',
        ),
        migrations.AddField(
            model_name='listaespera',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.profissional'),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.especialidade'),
        ),
    ]
