# Generated by Django 3.0.3 on 2022-10-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_usuarios', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(blank=True, choices=[('AG', 'Agendado'), ('AT', 'Atendido'), ('FN', 'Falta Não Justificada'), ('DM', 'Desmarcado')], default='AG', max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('especialidade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Especialidade')),
                ('odontograma', models.ManyToManyField(blank=True, to='agenda.Odontograma')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('procedimento', models.ManyToManyField(blank=True, to='agenda.Procedimento')),
                ('profissional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
                ('ubs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.Ubs')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
