# Generated by Django 3.0.3 on 2020-09-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_auto_20200927_2221'),
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(blank=True, choices=[('AG', 'Agendado'), ('AT', 'Atendido'), ('FJ', 'Justificada'), ('FH', 'Justificada na Hora'), ('FN', 'Não Justificada'), ('DM', 'Desmarcado/Profisssional'), ('CC', 'Cancelado'), ('BQ', 'Bloqueio'), ('PT', 'Particular'), ('AR', 'Atendido/Recepção')], default='AG', max_length=2)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
