# Generated by Django 3.0.3 on 2020-09-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(blank=True, choices=[('AG', 'Agendado'), ('AT', 'Atendido'), ('FN', 'Falta Não Justificada'), ('DM', 'Desmarcado')], default='AG', max_length=2),
        ),
    ]
