# Generated by Django 3.0.3 on 2022-10-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20221029_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='odontograma',
            field=models.ManyToManyField(blank=True, related_name='n', to='agenda.Odontograma'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ManyToManyField(blank=True, related_name='n', to='agenda.Procedimento'),
        ),
    ]
