# Generated by Django 3.0.3 on 2022-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20221029_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='odontograma',
            field=models.ManyToManyField(to='agenda.Odontograma'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ManyToManyField(to='agenda.Procedimento'),
        ),
    ]
