# Generated by Django 3.0.3 on 2022-10-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20221030_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'TipoConculta',
                'verbose_name_plural': 'TipoConculta',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipoconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.TipoConsulta'),
        ),
    ]
