# Generated by Django 3.0.3 on 2022-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20221031_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigilancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Vigilancia',
                'verbose_name_plural': 'Vigilancias',
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='vigilancia',
            field=models.ManyToManyField(to='agenda.Vigilancia'),
        ),
    ]
