# Generated by Django 3.0.3 on 2022-11-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20221101_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='vigilancia',
            field=models.ManyToManyField(blank=True, to='agenda.Vigilancia'),
        ),
    ]
