# Generated by Django 3.0.3 on 2022-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20221102_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='vigilancia',
            field=models.ManyToManyField(to='agenda.Vigilancia'),
        ),
    ]
