# Generated by Django 3.0.3 on 2022-11-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20221102_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipoconsulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.TipoConsulta'),
        ),
    ]
