# Generated by Django 3.1.7 on 2021-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20210417_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.BooleanField(blank=True, verbose_name='Tratamento Concluido'),
        ),
    ]
