# Generated by Django 3.1.7 on 2021-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20210417_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.CharField(blank=True, choices=[('IN', 'Iniciado'), ('CO', 'Concluido'), ('RE', 'RECUSA LIGAÇÃO')], max_length=2, verbose_name='tratamento'),
        ),
    ]
