# Generated by Django 3.1.7 on 2021-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20210418_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.CharField(blank=True, choices=[('IN', 'Iniciado'), ('CO', 'Concluido'), ('RE', 'NÃO ATENDE LIGAÇÃO')], default='RE', max_length=2, verbose_name='tratamento'),
        ),
    ]
