# Generated by Django 3.0.3 on 2020-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20201006_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(default=1, max_length=8, verbose_name='NCM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='preço'),
            preserve_default=False,
        ),
    ]
